vocab_size: 21128
embedding_dim: 512
n_heads: 8
hidden_dim: 768
kernel_size: [ 7, 5, 3, 3, 5, 7, 7, 5, 3, 3, 5, 7, 7 ]
padding: [3, 2, 1, 1, 2, 3, 3, 2, 1, 1, 2, 3, 3]
lr: 1e-3
b1: 0.999
b2: 0.9
prob: 0.8